import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
export default function Artifact({slug,compact=false}:{slug:string;compact?:boolean}){
 if(compact)return <div className={'artifact preview-artifact preview-'+slug} aria-label="산출물 재구성 예시"><div className="artifact-top"><strong>{slug==='devices'?'빵샤 / 계약·기기':slug==='pipedrive'?'디바이스 출고요청':'계약·청구·매출 데이터'}</strong><span>재구성 예시 · 가상 데이터</span></div>{slug==='devices'?<div className="preview-body"><div className="preview-record"><span>계약 A</span><strong>DEMO-A-001</strong><span>배정 · 출고 · 회수 이력</span></div><div className="preview-record"><span>계약 B</span><strong>DEMO-B-001</strong><span>배정 · 출고 · 교체 이력</span></div></div>:slug==='pipedrive'?<div className="preview-body"><div className="preview-fields"><span>모델명 · 수량</span><span>유상/무상 · 출고지</span><span>기기 설정 정보</span></div><div className="preview-flow">출고요청 완료 → 발행 활동 생성</div><small>발행 여부는 담당자 확인</small></div>:<div className="preview-body"><div className="preview-data"><strong>계약</strong><strong>청구주기</strong><strong>서비스</strong><span>계약 A</span><span>연</span><span>창고</span><span>계약 B</span><span>월</span><span>바이오</span></div><small>CRM 계약 링크 · 발생주의 여부</small></div>}</div>;
 return <div className={`artifact artifact-${slug} ${compact?'artifact-compact':''}`}>
 <div className="artifact-top"><strong>{slug==='devices'?'빵샤 / 계약·디바이스':slug==='pipedrive'?'출고요청 / 활동 템플릿':'매출 / 기준 데이터'}</strong><span>재구성 예시 · 가상 데이터</span></div>
 {slug==='devices'?<><div className="artifact-label">계약별 기기 배정·출고·교체·회수 이력</div><div className="contract-pair"><div><small>가상 거래처 A · 계약 A</small><strong>DEMO-A-001 · DEMO-A-002</strong><span>이번 검교정 교체 대상</span></div><div><small>가상 거래처 A · 계약 B</small><strong>DEMO-B-001 · DEMO-B-002</strong><span>다른 계약의 기기</span></div></div><div className="artifact-table"><Table><TableHeader><TableRow><TableHead>기기 시리얼</TableHead><TableHead>계약</TableHead><TableHead>기기 이력</TableHead><TableHead>회수 확인</TableHead></TableRow></TableHeader><TableBody>{[['DEMO-A-001','A','출고 → 교체 대상','미회수'],['DEMO-A-002','A','출고 → 회수','불량 기록'],['DEMO-B-001','B','출고','교체 대상 아님']].map(row=><TableRow key={row[0]}>{row.map((v,i)=><TableCell key={i}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></div><div className="artifact-chain">검교정 안내 → 교체·회수 이력 → 불량 기록·청구 검토</div></>:slug==='pipedrive'?<><div className="artifact-label">디바이스 출고요청 · 영업 담당자가 작성하는 공통 양식</div><dl className="request-fields">{[['모델명','DEMO-LOGGER'],['수량','10대'],['유상 / 무상','유상'],['출고지','가상 출고지 A'],['기기 설정 정보','가상 설정값 입력']].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="artifact-chain"><strong>출고요청 완료</strong><span>↓ 활동 자동 생성</span><strong>세금계산서 발행 검토</strong><small>유상·무상 정보 확인 후 담당자가 발행 여부 판단</small></div></>:<><div className="artifact-label">발행 내역에 계약·분류·귀속 정보를 보강</div><div className="data-before"><small>기존 항목</small><span>요청일자 · 품목 · 거래처 · 화주사 · 사업자번호 · 담당자 성함 · 담당자 메일 주소 · 수량 · 단가 · 공급가액 · 부가세 · 합계 · 세금계산서 발행일자</span></div><div className="artifact-table"><Table><TableHeader><TableRow>{['발행 건','계약 연결','판매/렌탈','서비스','계약기간','발행빈도','발생주의 여부','CRM 링크'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{[['DEMO-01','계약 A','렌탈','창고','2026.01–12','연','해당','가상 계약 A'],['DEMO-02','계약 B','판매','바이오','2026.09','일시','비해당','가상 계약 B']].map(row=><TableRow key={row[0]}>{row.map((v,i)=><TableCell key={i}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></div><div className="artifact-chain">추가·확장: 판매/렌탈 · 서비스 종류 · 품목 세분화 · 계약기간(시작~종료 / 년) · 발행 횟수 · 발행빈도 · 발생주의 여부 · 비고 · CRM 계약 링크</div></>}
 {!compact&&<p className="artifact-disclosure">{slug==='devices'?'저장소에서 확인한 기능 구조를 설명하기 위해 재구성한 화면입니다. 실제 빵샤 UI·작동 데모가 아니며 회사 시스템과 연결되지 않습니다.':slug==='pipedrive'?'설명해 주신 입력 항목과 자동화 규칙을 재구성했습니다. 실제 Pipedrive 화면 캡처가 아닙니다.':'항목 구조를 설명하기 위한 가상 예시입니다. 실제 매출 자료나 검증 완료 데이터를 표시한 것이 아닙니다. 입금액은 재무팀이 입력하는 항목입니다.'}</p>}
 </div>;
}
